### ISSUE TITLE
No module named 'vnpy_xtp.api.vnxtpmd'

### ISSUE THREAD

**Issue by iuhiyuh** [vnpy/vnpy_xtp#13]
env: vnpy-3.9.1.  vnpy-xtp-2.2.32.2.2 python-3.10

command: python run.py

content: run.py:
```python
from vnpy.event import EventEngine
from vnpy.trader.engine import MainEngine
from vnpy.trader.ui import MainWindow, create_qapp

from vnpy_xtp import XtpGateway


def main():
    """主入口函数"""
    qapp = create_qapp()

    event_engine = EventEngine()
    main_engine = MainEngine(event_engine)
    main_engine.add_gateway(XtpGateway)
    
    main_window = MainWindow(main_engine, event_engine)
    main_window.showMaximized()

    qapp.exec()


if __name__ == "__main__":
    main()
```

output: 
```shell
Traceback (most recent call last):
  File "/Users/zhangsan/workspace/vnpy-3.9.1/run.py", line 5, in <module>
    from vnpy_xtp import XtpGateway
  File "/Users/zhangsan/.pyenv/versions/miniconda3-latest/envs/vnpy/lib/python3.10/site-packages/vnpy_xtp/__init__.py", line 25, in <module>
    from .gateway import XtpGateway
  File "/Users/zhangsan/.pyenv/versions/miniconda3-latest/envs/vnpy/lib/python3.10/site-packages/vnpy_xtp/gateway/__init__.py", line 1, in <module>
    from .xtp_gateway import XtpGateway
  File "/Users/zhangsan/.pyenv/versions/miniconda3-latest/envs/vnpy/lib/python3.10/site-packages/vnpy_xtp/gateway/xtp_gateway.py", line 29, in <module>
    from ..api import MdApi, TdApi
  File "/Users/zhangsan/.pyenv/versions/miniconda3-latest/envs/vnpy/lib/python3.10/site-packages/vnpy_xtp/api/__init__.py", line 1, in <module>
    from .vnxtpmd import MdApi
ModuleNotFoundError: No module named 'vnpy_xtp.api.vnxtpmd'
```

**Comment by noranhe** [comment]
xtp没有提供mac支持
